version = 0.1

[default.deploy.parameters]
stack_name = "ai-personal-finance-dev"
resolve_s3 = true
s3_prefix = "ai-personal-finance-dev"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
